Universe              = vanilla
executable            = runMVADataMaker.sh
arguments             = $(ProcId) 0 1 
GetEnv                = True
requirements          = (OpSysAndVer =?= "CentOS7")
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
+JobFlavour           = "workday"
# RequestCpus           = 8
queue 10
